spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQLDialect
spring.datasource:
  url: jdbc:mysql://${HOST:localhost}:3306/itemdb
  username: ${USERNAME:root}
  password: ${PASS:root@123}
  driver-class-name: com.mysql.cj.jdbc.Driver