spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
spring.datasource:
  url: jdbc:mysql://localhost:3306/itemdb
  username: root
  password: root@123
  driver-class-name: com.mysql.cj.jdbc.Driver